#! /bin/bash
# Wrapper around jupyterhub-singleuser startup script to let us do some initial Matlab setup

# get the standard tooblox config for our Matlab sessions
if [ ! -e ~/toolbox-config.json ]
  then cp /srv/toolbox-toolbox/toolbox-config.json ~/toolbox-config.json
fi

# use Matlab and Toolbox Toolbox to obtain or update our notebook repository
# also revert any local edits to the official notebooks
# untracked notebooks should survive
if [ -e ~/toolboxes/notebooks/.git ]
  then git -C ~/toolboxes/notebooks reset --hard
fi
matlab -nosplash -nodesktop -r "tbDeployToolboxes('configPath', '~/toolbox-config.json', 'name', 'notebooks');exit;"

# if needed create user's own notebook dir
#  as expected in jupyterhub_config.py    
mkdir -p ~/toolboxes/notebooks

# proceed as normal
jupyterhub-singleuser "$@"

